
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Exercise_6 extends javax.swing.JFrame {

    /**
     * Creates new form Exercise_6
     */
    public Exercise_6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jButton1)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    
    Vehicule vehicule1 = new Vehicule("Audi");
    SpaceVehicule spaceVehicule1 = new SpaceVehicule("RP-1+ LOX", "NASA");
    Rocket rocket1 = new Rocket("3034 kN", "RP-1+ LOX", "ArianeSpace");

   
    LandVehicule landVehicule1 = new LandVehicule("Steel", "Ford");
    LandVehiculeWithEngine landVehiculeWithEngine1 = new LandVehiculeWithEngine("500 HP", "Aluminum", "Toyota");
    WheeledVehicule wheeledVehicule1 = new WheeledVehicule("4", "300 HP", "Carbon Fiber", "BMW");
    Car car1 = new Car("ABC123", "4", "250 HP", "Fiberglass", "Honda");
    TrackedVehicule trackedVehicule1 = new TrackedVehicule("10 mm", "1000 HP", "Titanium", "Caterpillar");
    Tank tank1 = new Tank("15 mm","2000 HP", "1500 HP", "Composite", "Leclerc");
    LandVehiculeWithoutEngine landVehiculeWithoutEngine1 = new LandVehiculeWithoutEngine("Wind", "Wood", "Hobie");
    Sailboat sailboat1 = new Sailboat("50 sqm", "Wind", "Fiberglass", "Beneteau");

    
    ArrayList<Vehicule> vehiculeTable = new ArrayList<Vehicule>(0);;

 
    vehiculeTable.add(vehicule1);
    vehiculeTable.add(spaceVehicule1);
    vehiculeTable.add(rocket1);
    vehiculeTable.add(landVehicule1);
    vehiculeTable.add(landVehiculeWithEngine1);
    vehiculeTable.add(wheeledVehicule1);
    vehiculeTable.add(car1);
    vehiculeTable.add(trackedVehicule1);
    vehiculeTable.add(tank1);
    vehiculeTable.add(landVehiculeWithoutEngine1);
    vehiculeTable.add(sailboat1);

    
    for (int i = 0; i < vehiculeTable.size(); i++) {
        System.out.println(vehiculeTable.get(i).toString());
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercise_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercise_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercise_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercise_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercise_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
